package com.routecj.admin.presentation.godowns

import android.widget.Toast
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.navigation.NavController
import com.routecj.admin.core.util.Constants
import com.routecj.admin.core.util.Result
import com.routecj.admin.domain.model.Order
import com.routecj.admin.domain.model.OrderStatus
import com.routecj.admin.domain.model.PaymentMethod
import com.routecj.admin.domain.model.PaymentStatus
import com.routecj.admin.presentation.components.*
import com.routecj.admin.presentation.orders.OrdersViewModel
import com.routecj.admin.ui.theme.Primary
import com.routecj.admin.ui.theme.Secondary
import java.text.SimpleDateFormat
import java.util.*

enum class ParcelEntryMode {
    CUSTOMER_PARCEL,
    MANUAL_ENTRY
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AddParcelScreen(
    navController: NavController,
    viewModel: OrdersViewModel = hiltViewModel()
) {
    val context = LocalContext.current
    var selectedMode by remember { mutableStateOf(ParcelEntryMode.CUSTOMER_PARCEL) }

    // --- State for Customer Parcel Tab ---
    val allOrdersState by viewModel.ordersState.collectAsStateWithLifecycle()
    var customerSearchQuery by remember { mutableStateOf("") }

    // --- State for Manual Entry Tab ---
    val autoGeneratedOrderNumber = remember { "PCL-" + SimpleDateFormat("yyyyMMdd", Locale.getDefault()).format(Date()) + "-" + (1000..9999).random() }
    var orderNumber by remember { mutableStateOf(autoGeneratedOrderNumber) }
    var customerName by remember { mutableStateOf("") }
    var customerPhone by remember { mutableStateOf("") }
    var pickupAddress by remember { mutableStateOf("") }
    var pickupPincode by remember { mutableStateOf("") }
    var deliveryAddress by remember { mutableStateOf("") }
    var deliveryPincode by remember { mutableStateOf("") }

    var itemName by remember { mutableStateOf("") }
    var itemDescription by remember { mutableStateOf("") }
    var quantityText by remember { mutableStateOf("1") }
    var weightText by remember { mutableStateOf("") }
    var lengthText by remember { mutableStateOf("") }
    var widthText by remember { mutableStateOf("") }
    var heightText by remember { mutableStateOf("") }
    var isFragile by remember { mutableStateOf(false) }
    var specialInstructions by remember { mutableStateOf("") }
    var priority by remember { mutableStateOf("Medium") }

    // --- State for Payment Details (Defaults to PENDING) ---
    var paymentStatus by remember { mutableStateOf(PaymentStatus.PENDING) }
    var paymentMethod by remember { mutableStateOf(PaymentMethod.CASH) }
    var paymentAmountText by remember { mutableStateOf("") }
    var transactionId by remember { mutableStateOf("") }
    var paymentNotes by remember { mutableStateOf("") }

    var validationError by remember { mutableStateOf<String?>(null) }
    val actionState by viewModel.actionState.collectAsStateWithLifecycle()

    LaunchedEffect(actionState) {
        if (actionState is Result.Success) {
            Toast.makeText(context, "Parcel created successfully", Toast.LENGTH_SHORT).show()
            viewModel.clearActionState()
            navController.popBackStack()
        } else if (actionState is Result.Error) {
            Toast.makeText(context, (actionState as Result.Error).message, Toast.LENGTH_LONG).show()
            viewModel.clearActionState()
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Add Parcel", fontWeight = FontWeight.ExtraBold) },
                navigationIcon = {
                    IconButton(onClick = { navController.popBackStack() }) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = MaterialTheme.colorScheme.background)
            )
        },
        containerColor = MaterialTheme.colorScheme.background
    ) { paddingValues ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
        ) {
            // Mode Selector
            Surface(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(horizontal = 16.dp, vertical = 8.dp),
                shape = RoundedCornerShape(16.dp),
                color = Color(0xFF1E293B)
            ) {
                Row(
                    modifier = Modifier.padding(4.dp),
                    horizontalArrangement = Arrangement.spacedBy(4.dp)
                ) {
                    // Option A: Customer Parcel
                    Surface(
                        modifier = Modifier
                            .weight(1f)
                            .clickable { selectedMode = ParcelEntryMode.CUSTOMER_PARCEL },
                        shape = RoundedCornerShape(12.dp),
                        color = if (selectedMode == ParcelEntryMode.CUSTOMER_PARCEL) Primary else Color.Transparent
                    ) {
                        Box(
                            modifier = Modifier.padding(vertical = 12.dp),
                            contentAlignment = Alignment.Center
                        ) {
                            Text(
                                text = "Customer Parcel",
                                fontWeight = FontWeight.Bold,
                                fontSize = 13.sp,
                                color = if (selectedMode == ParcelEntryMode.CUSTOMER_PARCEL) Color.Black else Color(0xFF94A3B8)
                            )
                        }
                    }

                    // Option B: Manual Entry
                    Surface(
                        modifier = Modifier
                            .weight(1f)
                            .clickable { selectedMode = ParcelEntryMode.MANUAL_ENTRY },
                        shape = RoundedCornerShape(12.dp),
                        color = if (selectedMode == ParcelEntryMode.MANUAL_ENTRY) Primary else Color.Transparent
                    ) {
                        Box(
                            modifier = Modifier.padding(vertical = 12.dp),
                            contentAlignment = Alignment.Center
                        ) {
                            Text(
                                text = "Manual Entry",
                                fontWeight = FontWeight.Bold,
                                fontSize = 13.sp,
                                color = if (selectedMode == ParcelEntryMode.MANUAL_ENTRY) Color.Black else Color(0xFF94A3B8)
                            )
                        }
                    }
                }
            }

            when (selectedMode) {
                ParcelEntryMode.CUSTOMER_PARCEL -> {
                    // Customer Parcel Search & List
                    Column(
                        modifier = Modifier
                            .fillMaxSize()
                            .padding(16.dp)
                    ) {
                        OutlinedTextField(
                            value = customerSearchQuery,
                            onValueChange = { customerSearchQuery = it },
                            placeholder = { Text("Search by Order #, Customer, Destination...", color = Color(0xFF94A3B8)) },
                            leadingIcon = { Icon(Icons.Default.Search, contentDescription = "Search", tint = Color(0xFF64748B)) },
                            trailingIcon = {
                                if (customerSearchQuery.isNotBlank()) {
                                    IconButton(onClick = { customerSearchQuery = "" }) {
                                        Icon(Icons.Default.Close, contentDescription = "Clear", tint = Color(0xFF64748B))
                                    }
                                }
                            },
                            singleLine = true,
                            shape = RoundedCornerShape(14.dp),
                            modifier = Modifier.fillMaxWidth(),
                            colors = routeCJTextFieldColors(
                                containerColor = Color.White,
                                textColor = Color(0xFF0F172A),
                                unfocusedBorderColor = Color(0xFFCBD5E1)
                            )
                        )

                        Spacer(modifier = Modifier.height(16.dp))

                        when (val state = allOrdersState) {
                            is Result.Loading -> PremiumLoadingState(message = "Loading customer orders...")
                            is Result.Error -> PremiumErrorState(message = state.message, onRetry = { viewModel.retry() })
                            is Result.Success -> {
                                val eligibleOrders = state.data.filter { order ->
                                    val status = order.status
                                    val isEligibleStatus = status == OrderStatus.PENDING ||
                                            status == OrderStatus.PENDING_GODOWN_REVIEW ||
                                            status == OrderStatus.PICKED_UP ||
                                            status == OrderStatus.ASSIGNED ||
                                            status == OrderStatus.QR_GENERATED

                                    val matchesQuery = customerSearchQuery.isBlank() ||
                                            order.orderNumber.contains(customerSearchQuery, ignoreCase = true) ||
                                            order.customerName.contains(customerSearchQuery, ignoreCase = true) ||
                                            order.deliveryLocation.contains(customerSearchQuery, ignoreCase = true) ||
                                            order.pickupLocation.contains(customerSearchQuery, ignoreCase = true)

                                    isEligibleStatus && matchesQuery
                                }

                                if (eligibleOrders.isEmpty()) {
                                    PremiumEmptyState(
                                        message = if (customerSearchQuery.isBlank()) "No customer parcels pending godown processing." else "No matching customer parcels found.",
                                        icon = Icons.Default.Inventory2
                                    )
                                } else {
                                    LazyColumn(
                                        verticalArrangement = Arrangement.spacedBy(14.dp),
                                        contentPadding = PaddingValues(bottom = 24.dp)
                                    ) {
                                        items(eligibleOrders) { order ->
                                            BentoCard(
                                                modifier = Modifier.fillMaxWidth()
                                            ) {
                                                Row(
                                                    modifier = Modifier.fillMaxWidth(),
                                                    horizontalArrangement = Arrangement.SpaceBetween,
                                                    verticalAlignment = Alignment.CenterVertically
                                                ) {
                                                    Column {
                                                        Text(
                                                            text = order.orderNumber,
                                                            fontWeight = FontWeight.ExtraBold,
                                                            fontSize = 16.sp,
                                                            color = Secondary
                                                        )
                                                        Text(
                                                            text = "Customer: ${order.customerName}",
                                                            fontSize = 13.sp,
                                                            color = Color(0xFF64748B),
                                                            fontWeight = FontWeight.Medium
                                                        )
                                                    }
                                                    PremiumStatusChip(
                                                        text = order.status.name.replace("_", " "),
                                                        color = when (order.status) {
                                                            OrderStatus.READY_FOR_DISPATCH -> Color(0xFF22C55E)
                                                            OrderStatus.PENDING_GODOWN_REVIEW -> Color(0xFFF59E0B)
                                                            else -> Primary
                                                        }
                                                    )
                                                }

                                                Spacer(modifier = Modifier.height(10.dp))
                                                val originPin = if (order.pickupPincode.isNotBlank()) " (${order.pickupPincode})" else ""
                                                val destPin = if (order.deliveryPincode.isNotBlank()) " (${order.deliveryPincode})" else ""
                                                val originDisplay = (order.pickupAddress.ifBlank { order.pickupLocation }).ifBlank { "Origin" }
                                                val destDisplay = (order.deliveryAddress.ifBlank { order.deliveryLocation }).ifBlank { "Destination" }
                                                Column(
                                                    modifier = Modifier.fillMaxWidth(),
                                                    verticalArrangement = Arrangement.spacedBy(4.dp)
                                                ) {
                                                    Text(
                                                        text = "From: $originDisplay$originPin",
                                                        fontSize = 12.sp,
                                                        color = Color(0xFFCBD5E1)
                                                    )
                                                    Text(
                                                        text = "To: $destDisplay$destPin",
                                                        fontSize = 12.sp,
                                                        color = Color(0xFFCBD5E1)
                                                    )
                                                }

                                                Spacer(modifier = Modifier.height(14.dp))
                                                Button(
                                                    onClick = {
                                                        navController.navigate(Constants.NavigationRoutes.PARCEL_DETAILS.replace("{parcelId}", order.id))
                                                    },
                                                    modifier = Modifier.fillMaxWidth().height(46.dp),
                                                    shape = RoundedCornerShape(12.dp),
                                                    colors = ButtonDefaults.buttonColors(containerColor = Primary)
                                                ) {
                                                    Icon(Icons.Default.Check, contentDescription = null, tint = Color.Black)
                                                    Spacer(modifier = Modifier.width(6.dp))
                                                    Text("Use This Parcel", fontWeight = FontWeight.Bold, color = Color.Black)
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

                ParcelEntryMode.MANUAL_ENTRY -> {
                    // Manual Parcel Entry Form
                    LazyColumn(
                        modifier = Modifier
                            .fillMaxSize()
                            .padding(horizontal = 16.dp),
                        verticalArrangement = Arrangement.spacedBy(16.dp),
                        contentPadding = PaddingValues(top = 8.dp, bottom = 48.dp)
                    ) {
                        // Section 1: Parcel & Customer Details
                        item {
                            BentoCard(modifier = Modifier.fillMaxWidth()) {
                                Text(
                                    text = "PARCEL & CUSTOMER INFORMATION",
                                    style = MaterialTheme.typography.labelSmall,
                                    fontWeight = FontWeight.Black,
                                    color = Color(0xFF94A3B8)
                                )
                                Spacer(modifier = Modifier.height(12.dp))

                                OutlinedTextField(
                                    value = orderNumber,
                                    onValueChange = { orderNumber = it },
                                    label = { Text("Parcel ID / Reference ID *") },
                                    singleLine = true,
                                    modifier = Modifier.fillMaxWidth(),
                                    shape = RoundedCornerShape(12.dp),
                                    colors = routeCJTextFieldColors()
                                )
                                Spacer(modifier = Modifier.height(10.dp))

                                OutlinedTextField(
                                    value = customerName,
                                    onValueChange = { customerName = it },
                                    label = { Text("Customer Name *") },
                                    singleLine = true,
                                    modifier = Modifier.fillMaxWidth(),
                                    shape = RoundedCornerShape(12.dp),
                                    colors = routeCJTextFieldColors()
                                )
                                Spacer(modifier = Modifier.height(10.dp))

                                OutlinedTextField(
                                    value = customerPhone,
                                    onValueChange = { customerPhone = it },
                                    label = { Text("Customer Phone *") },
                                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Phone),
                                    singleLine = true,
                                    modifier = Modifier.fillMaxWidth(),
                                    shape = RoundedCornerShape(12.dp),
                                    colors = routeCJTextFieldColors()
                                )
                            }
                        }

                        // Section 2: Pickup Location
                        item {
                            BentoCard(modifier = Modifier.fillMaxWidth()) {
                                Text(
                                    text = "PICKUP LOCATION",
                                    style = MaterialTheme.typography.labelSmall,
                                    fontWeight = FontWeight.Black,
                                    color = Color(0xFF64748B)
                                )
                                Spacer(modifier = Modifier.height(12.dp))

                                OutlinedTextField(
                                    value = pickupAddress,
                                    onValueChange = { pickupAddress = it },
                                    label = { Text("Pickup Address *") },
                                    placeholder = { Text("Enter origin/godown street address") },
                                    singleLine = true,
                                    modifier = Modifier.fillMaxWidth(),
                                    shape = RoundedCornerShape(12.dp),
                                    colors = routeCJTextFieldColors()
                                )
                                Spacer(modifier = Modifier.height(10.dp))

                                OutlinedTextField(
                                    value = pickupPincode,
                                    onValueChange = { input ->
                                        // Numeric only, max 6 digits
                                        val digits = input.filter { it.isDigit() }.take(6)
                                        pickupPincode = digits
                                    },
                                    label = { Text("Pickup PIN Code * (6 Digits)") },
                                    placeholder = { Text("e.g. 500001") },
                                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                                    singleLine = true,
                                    modifier = Modifier.fillMaxWidth(),
                                    shape = RoundedCornerShape(12.dp),
                                    colors = routeCJTextFieldColors()
                                )
                            }
                        }

                        // Section 3: Delivery Location
                        item {
                            BentoCard(modifier = Modifier.fillMaxWidth()) {
                                Text(
                                    text = "DELIVERY LOCATION",
                                    style = MaterialTheme.typography.labelSmall,
                                    fontWeight = FontWeight.Black,
                                    color = Color(0xFF64748B)
                                )
                                Spacer(modifier = Modifier.height(12.dp))

                                OutlinedTextField(
                                    value = deliveryAddress,
                                    onValueChange = { deliveryAddress = it },
                                    label = { Text("Delivery Address *") },
                                    placeholder = { Text("Enter destination delivery address") },
                                    singleLine = true,
                                    modifier = Modifier.fillMaxWidth(),
                                    shape = RoundedCornerShape(12.dp),
                                    colors = routeCJTextFieldColors()
                                )
                                Spacer(modifier = Modifier.height(10.dp))

                                OutlinedTextField(
                                    value = deliveryPincode,
                                    onValueChange = { input ->
                                        // Numeric only, max 6 digits
                                        val digits = input.filter { it.isDigit() }.take(6)
                                        deliveryPincode = digits
                                    },
                                    label = { Text("Delivery PIN Code * (6 Digits)") },
                                    placeholder = { Text("e.g. 530001") },
                                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                                    singleLine = true,
                                    modifier = Modifier.fillMaxWidth(),
                                    shape = RoundedCornerShape(12.dp),
                                    colors = routeCJTextFieldColors()
                                )
                            }
                        }

                        // Section 4: Item Information
                        item {
                            BentoCard(modifier = Modifier.fillMaxWidth()) {
                                Text(
                                    text = "ITEM DETAILS & SPECIFICATIONS",
                                    style = MaterialTheme.typography.labelSmall,
                                    fontWeight = FontWeight.Black,
                                    color = Color(0xFF64748B)
                                )
                                Spacer(modifier = Modifier.height(12.dp))

                                OutlinedTextField(
                                    value = itemName,
                                    onValueChange = { itemName = it },
                                    label = { Text("Item Name * (e.g. Laptop, Medical Supplies)") },
                                    singleLine = true,
                                    modifier = Modifier.fillMaxWidth(),
                                    shape = RoundedCornerShape(12.dp),
                                    colors = routeCJTextFieldColors()
                                )
                                Spacer(modifier = Modifier.height(10.dp))

                                OutlinedTextField(
                                    value = itemDescription,
                                    onValueChange = { itemDescription = it },
                                    label = { Text("Item Description") },
                                    maxLines = 2,
                                    modifier = Modifier.fillMaxWidth(),
                                    shape = RoundedCornerShape(12.dp),
                                    colors = routeCJTextFieldColors()
                                )
                                Spacer(modifier = Modifier.height(10.dp))

                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.spacedBy(10.dp)
                                ) {
                                    OutlinedTextField(
                                        value = quantityText,
                                        onValueChange = { quantityText = it },
                                        label = { Text("Quantity *") },
                                        keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
                                        singleLine = true,
                                        modifier = Modifier.weight(1f),
                                        shape = RoundedCornerShape(12.dp),
                                        colors = routeCJTextFieldColors()
                                    )
                                    OutlinedTextField(
                                        value = weightText,
                                        onValueChange = { weightText = it },
                                        label = { Text("Weight (kg) *") },
                                        keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Decimal),
                                        singleLine = true,
                                        modifier = Modifier.weight(1f),
                                        shape = RoundedCornerShape(12.dp),
                                        colors = routeCJTextFieldColors()
                                    )
                                }
                                Spacer(modifier = Modifier.height(10.dp))

                                Text(
                                    text = "Dimensions (cm) - Optional",
                                    fontSize = 12.sp,
                                    color = Color(0xFF64748B),
                                    fontWeight = FontWeight.SemiBold
                                )
                                Spacer(modifier = Modifier.height(6.dp))
                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                                ) {
                                    OutlinedTextField(
                                        value = lengthText,
                                        onValueChange = { lengthText = it },
                                        label = { Text("L") },
                                        keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Decimal),
                                        singleLine = true,
                                        modifier = Modifier.weight(1f),
                                        shape = RoundedCornerShape(12.dp),
                                        colors = routeCJTextFieldColors()
                                    )
                                    OutlinedTextField(
                                        value = widthText,
                                        onValueChange = { widthText = it },
                                        label = { Text("W") },
                                        keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Decimal),
                                        singleLine = true,
                                        modifier = Modifier.weight(1f),
                                        shape = RoundedCornerShape(12.dp),
                                        colors = routeCJTextFieldColors()
                                    )
                                    OutlinedTextField(
                                        value = heightText,
                                        onValueChange = { heightText = it },
                                        label = { Text("H") },
                                        keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Decimal),
                                        singleLine = true,
                                        modifier = Modifier.weight(1f),
                                        shape = RoundedCornerShape(12.dp),
                                        colors = routeCJTextFieldColors()
                                    )
                                }
                            }
                        }

                        // Section 5: Handling & Special Notes
                        item {
                            BentoCard(modifier = Modifier.fillMaxWidth()) {
                                Text(
                                    text = "HANDLING & PRIORITY",
                                    style = MaterialTheme.typography.labelSmall,
                                    fontWeight = FontWeight.Black,
                                    color = Color(0xFF64748B)
                                )
                                Spacer(modifier = Modifier.height(12.dp))

                                Row(
                                    modifier = Modifier
                                        .fillMaxWidth()
                                        .clickable { isFragile = !isFragile }
                                        .padding(vertical = 4.dp),
                                    verticalAlignment = Alignment.CenterVertically,
                                    horizontalArrangement = Arrangement.SpaceBetween
                                ) {
                                    Row(verticalAlignment = Alignment.CenterVertically) {
                                        Icon(
                                            Icons.Default.Warning,
                                            contentDescription = null,
                                            tint = if (isFragile) Color(0xFFEF4444) else Color(0xFF64748B)
                                        )
                                        Spacer(modifier = Modifier.width(8.dp))
                                        Column {
                                            Text("Fragile Item", fontWeight = FontWeight.Bold, color = Secondary)
                                            Text("Requires delicate handling and upright storage", fontSize = 11.sp, color = Color(0xFF64748B))
                                        }
                                    }
                                    Switch(
                                        checked = isFragile,
                                        onCheckedChange = { isFragile = it },
                                        colors = SwitchDefaults.colors(checkedThumbColor = Color(0xFFEF4444), checkedTrackColor = Color(0xFFEF4444).copy(alpha = 0.3f))
                                    )
                                }

                                Spacer(modifier = Modifier.height(10.dp))

                                OutlinedTextField(
                                    value = specialInstructions,
                                    onValueChange = { specialInstructions = it },
                                    label = { Text("Special Handling Notes (Optional)") },
                                    maxLines = 3,
                                    modifier = Modifier.fillMaxWidth(),
                                    shape = RoundedCornerShape(12.dp),
                                    colors = routeCJTextFieldColors()
                                )
                            }
                        }

                        // Section 6: Payment Details
                        item {
                            BentoCard(modifier = Modifier.fillMaxWidth()) {
                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.SpaceBetween,
                                    verticalAlignment = Alignment.CenterVertically
                                ) {
                                    Text(
                                        text = "PAYMENT DETAILS",
                                        style = MaterialTheme.typography.labelSmall,
                                        fontWeight = FontWeight.Black,
                                        color = Color(0xFF64748B)
                                    )
                                    Surface(
                                        color = when (paymentStatus) {
                                            PaymentStatus.PAID -> Color(0xFF10B981).copy(alpha = 0.15f)
                                            PaymentStatus.PENDING -> Color(0xFFF59E0B).copy(alpha = 0.15f)
                                            PaymentStatus.PARTIALLY_PAID -> Color(0xFF3B82F6).copy(alpha = 0.15f)
                                            PaymentStatus.COD -> Color(0xFF8B5CF6).copy(alpha = 0.15f)
                                            PaymentStatus.FAILED -> Color(0xFFEF4444).copy(alpha = 0.15f)
                                            PaymentStatus.REFUNDED -> Color(0xFF6B7280).copy(alpha = 0.15f)
                                        },
                                        shape = RoundedCornerShape(6.dp)
                                    ) {
                                        Text(
                                            text = paymentStatus.name.replace("_", " "),
                                            color = when (paymentStatus) {
                                                PaymentStatus.PAID -> Color(0xFF10B981)
                                                PaymentStatus.PENDING -> Color(0xFFF59E0B)
                                                PaymentStatus.PARTIALLY_PAID -> Color(0xFF3B82F6)
                                                PaymentStatus.COD -> Color(0xFF8B5CF6)
                                                PaymentStatus.FAILED -> Color(0xFFEF4444)
                                                PaymentStatus.REFUNDED -> Color(0xFF9CA3AF)
                                            },
                                            fontSize = 10.sp,
                                            fontWeight = FontWeight.ExtraBold,
                                            modifier = Modifier.padding(horizontal = 8.dp, vertical = 3.dp)
                                        )
                                    }
                                }
                                Spacer(modifier = Modifier.height(12.dp))

                                // Payment Status Selector
                                Text("Payment Status *", fontSize = 12.sp, fontWeight = FontWeight.Bold, color = Color(0xFF64748B))
                                Spacer(modifier = Modifier.height(6.dp))
                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.spacedBy(6.dp)
                                ) {
                                    listOf(PaymentStatus.PENDING, PaymentStatus.PAID, PaymentStatus.COD).forEach { status ->
                                        val isSelected = paymentStatus == status
                                        FilterChip(
                                            selected = isSelected,
                                            onClick = {
                                                paymentStatus = status
                                                if (status == PaymentStatus.COD) {
                                                    paymentMethod = PaymentMethod.COD
                                                } else if (paymentMethod == PaymentMethod.COD) {
                                                    paymentMethod = PaymentMethod.CASH
                                                }
                                            },
                                            label = { Text(status.name.replace("_", " "), fontSize = 11.sp, fontWeight = if (isSelected) FontWeight.ExtraBold else FontWeight.Medium) },
                                            modifier = Modifier.weight(1f),
                                            colors = FilterChipDefaults.filterChipColors(
                                                selectedContainerColor = Primary,
                                                selectedLabelColor = Color.Black
                                            )
                                        )
                                    }
                                }
                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.spacedBy(6.dp)
                                ) {
                                    listOf(PaymentStatus.PARTIALLY_PAID, PaymentStatus.FAILED, PaymentStatus.REFUNDED).forEach { status ->
                                        val isSelected = paymentStatus == status
                                        FilterChip(
                                            selected = isSelected,
                                            onClick = {
                                                paymentStatus = status
                                                if (status == PaymentStatus.COD) {
                                                    paymentMethod = PaymentMethod.COD
                                                } else if (paymentMethod == PaymentMethod.COD) {
                                                    paymentMethod = PaymentMethod.CASH
                                                }
                                            },
                                            label = { Text(status.name.replace("_", " "), fontSize = 10.sp, fontWeight = if (isSelected) FontWeight.ExtraBold else FontWeight.Medium) },
                                            modifier = Modifier.weight(1f),
                                            colors = FilterChipDefaults.filterChipColors(
                                                selectedContainerColor = Primary,
                                                selectedLabelColor = Color.Black
                                            )
                                        )
                                    }
                                }

                                Spacer(modifier = Modifier.height(10.dp))

                                // Payment Method Selector
                                Text("Payment Method *", fontSize = 12.sp, fontWeight = FontWeight.Bold, color = Color(0xFF64748B))
                                Spacer(modifier = Modifier.height(6.dp))
                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.spacedBy(6.dp)
                                ) {
                                    listOf(PaymentMethod.CASH, PaymentMethod.UPI, PaymentMethod.CARD).forEach { method ->
                                        val isSelected = paymentMethod == method
                                        FilterChip(
                                            selected = isSelected,
                                            onClick = {
                                                paymentMethod = method
                                                if (method == PaymentMethod.COD) paymentStatus = PaymentStatus.COD
                                            },
                                            label = { Text(method.name.replace("_", " "), fontSize = 11.sp, fontWeight = if (isSelected) FontWeight.ExtraBold else FontWeight.Medium) },
                                            modifier = Modifier.weight(1f),
                                            colors = FilterChipDefaults.filterChipColors(
                                                selectedContainerColor = Primary,
                                                selectedLabelColor = Color.Black
                                            )
                                        )
                                    }
                                }
                                Row(
                                    modifier = Modifier.fillMaxWidth(),
                                    horizontalArrangement = Arrangement.spacedBy(6.dp)
                                ) {
                                    listOf(PaymentMethod.BANK_TRANSFER, PaymentMethod.COD, PaymentMethod.OTHER).forEach { method ->
                                        val isSelected = paymentMethod == method
                                        FilterChip(
                                            selected = isSelected,
                                            onClick = {
                                                paymentMethod = method
                                                if (method == PaymentMethod.COD) paymentStatus = PaymentStatus.COD
                                            },
                                            label = { Text(method.name.replace("_", " "), fontSize = 10.sp, fontWeight = if (isSelected) FontWeight.ExtraBold else FontWeight.Medium) },
                                            modifier = Modifier.weight(1f),
                                            colors = FilterChipDefaults.filterChipColors(
                                                selectedContainerColor = Primary,
                                                selectedLabelColor = Color.Black
                                            )
                                        )
                                    }
                                }

                                Spacer(modifier = Modifier.height(10.dp))

                                // Amount Field
                                OutlinedTextField(
                                    value = paymentAmountText,
                                    onValueChange = { input ->
                                        if (input.isEmpty() || input.matches(Regex("""^\d*\.?\d*$"""))) {
                                            paymentAmountText = input
                                        }
                                    },
                                    label = { Text("Payment Amount (₹)") },
                                    placeholder = { Text("e.g. 1500.00") },
                                    prefix = { Text("₹ ", fontWeight = FontWeight.Bold, color = Primary) },
                                    keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Decimal),
                                    singleLine = true,
                                    modifier = Modifier.fillMaxWidth(),
                                    shape = RoundedCornerShape(12.dp),
                                    colors = routeCJTextFieldColors()
                                )

                                if (paymentMethod == PaymentMethod.UPI) {
                                    Spacer(modifier = Modifier.height(10.dp))
                                    UpiPaymentQrCard(
                                        amount = paymentAmountText.toDoubleOrNull() ?: 0.0,
                                        orderNumber = orderNumber
                                    )
                                }

                                Spacer(modifier = Modifier.height(10.dp))

                                // Transaction ID
                                val isElectronic = paymentMethod == PaymentMethod.UPI || paymentMethod == PaymentMethod.CARD || paymentMethod == PaymentMethod.BANK_TRANSFER
                                val isPaidState = paymentStatus == PaymentStatus.PAID || paymentStatus == PaymentStatus.PARTIALLY_PAID
                                OutlinedTextField(
                                    value = transactionId,
                                    onValueChange = { transactionId = it },
                                    label = {
                                        Text(if (isElectronic && isPaidState) "Transaction / Reference ID *" else "Transaction / Reference ID (Optional)")
                                    },
                                    placeholder = { Text("e.g. UPI-9876543210 or TXN123456") },
                                    singleLine = true,
                                    modifier = Modifier.fillMaxWidth(),
                                    shape = RoundedCornerShape(12.dp),
                                    colors = routeCJTextFieldColors()
                                )

                                Spacer(modifier = Modifier.height(10.dp))

                                // Payment Notes
                                OutlinedTextField(
                                    value = paymentNotes,
                                    onValueChange = { paymentNotes = it },
                                    label = { Text("Payment Notes (Optional)") },
                                    placeholder = { Text("e.g. Customer paid advance ₹500 through UPI") },
                                    maxLines = 2,
                                    modifier = Modifier.fillMaxWidth(),
                                    shape = RoundedCornerShape(12.dp),
                                    colors = routeCJTextFieldColors()
                                )
                            }
                        }

                        // Validation Error Display
                        if (validationError != null) {
                            item {
                                Surface(
                                    shape = RoundedCornerShape(12.dp),
                                    color = Color(0xFFEF4444).copy(alpha = 0.15f),
                                    border = androidx.compose.foundation.BorderStroke(1.dp, Color(0xFFEF4444).copy(alpha = 0.5f)),
                                    modifier = Modifier.fillMaxWidth()
                                ) {
                                    Row(
                                        modifier = Modifier.padding(14.dp),
                                        verticalAlignment = Alignment.CenterVertically
                                    ) {
                                        Icon(Icons.Default.Error, contentDescription = null, tint = Color(0xFFEF4444))
                                        Spacer(modifier = Modifier.width(10.dp))
                                        Text(
                                            text = validationError ?: "",
                                            color = Color(0xFFFCA5A5),
                                            fontSize = 13.sp,
                                            fontWeight = FontWeight.Medium
                                        )
                                    }
                                }
                            }
                        }

                        // Submit Button
                        item {
                            Button(
                                onClick = {
                                    // Validate
                                    if (orderNumber.isBlank()) {
                                        validationError = "Parcel / Order reference ID is required."
                                        return@Button
                                    }
                                    if (customerName.isBlank()) {
                                        validationError = "Customer Name is required."
                                        return@Button
                                    }
                                    if (customerPhone.isBlank() || customerPhone.length < 7) {
                                        validationError = "Valid Customer Phone number is required."
                                        return@Button
                                    }
                                    if (pickupAddress.isBlank()) {
                                        validationError = "Pickup Address is required."
                                        return@Button
                                    }
                                    if (pickupPincode.length != 6 || !pickupPincode.all { it.isDigit() }) {
                                        validationError = "Enter a valid 6-digit PIN code."
                                        return@Button
                                    }
                                    if (deliveryAddress.isBlank()) {
                                        validationError = "Delivery Address is required."
                                        return@Button
                                    }
                                    if (deliveryPincode.length != 6 || !deliveryPincode.all { it.isDigit() }) {
                                        validationError = "Enter a valid 6-digit PIN code."
                                        return@Button
                                    }
                                    if (itemName.isBlank()) {
                                        validationError = "Item Name is required."
                                        return@Button
                                    }

                                    val qty = quantityText.toIntOrNull() ?: 0
                                    if (qty <= 0) {
                                        validationError = "Quantity must be greater than 0."
                                        return@Button
                                    }

                                    val weightVal = weightText.toDoubleOrNull() ?: -1.0
                                    if (weightVal <= 0.0) {
                                        validationError = "Weight must be greater than 0 kg."
                                        return@Button
                                    }

                                    val amt = paymentAmountText.toDoubleOrNull() ?: 0.0
                                    if (amt < 0.0) {
                                        validationError = "Payment amount cannot be negative."
                                        return@Button
                                    }

                                    val isElectronicMethod = paymentMethod == PaymentMethod.UPI || paymentMethod == PaymentMethod.CARD || paymentMethod == PaymentMethod.BANK_TRANSFER
                                    val isPaidOrPartial = paymentStatus == PaymentStatus.PAID || paymentStatus == PaymentStatus.PARTIALLY_PAID
                                    if (isPaidOrPartial && isElectronicMethod && transactionId.isBlank()) {
                                        validationError = "Transaction / Reference ID is required for ${paymentMethod.name.replace("_", " ")} payments."
                                        return@Button
                                    }

                                    validationError = null

                                    val currentUser = com.google.firebase.auth.FirebaseAuth.getInstance().currentUser
                                    val currentUid = currentUser?.uid ?: ""
                                    val currentEmail = currentUser?.email ?: "ADMIN003"

                                    val paymentDate = if (isPaidOrPartial) Date() else null

                                    val newOrder = Order(
                                        id = UUID.randomUUID().toString(),
                                        orderNumber = orderNumber.trim(),
                                        customerName = customerName.trim(),
                                        customerPhone = customerPhone.trim(),
                                        customerAddress = deliveryAddress.trim(),
                                        pickupLocation = pickupAddress.trim(),
                                        deliveryLocation = deliveryAddress.trim(),
                                        pickupAddress = pickupAddress.trim(),
                                        pickupPincode = pickupPincode.trim(),
                                        deliveryAddress = deliveryAddress.trim(),
                                        deliveryPincode = deliveryPincode.trim(),
                                        orderType = "STANDARD_PARCEL",
                                        weight = weightVal,
                                        quantity = qty,
                                        priority = priority,
                                        paymentStatus = paymentStatus.name,
                                        paymentMethod = paymentMethod.name,
                                        paymentAmount = amt,
                                        transactionId = transactionId.trim(),
                                        paymentTimestamp = paymentDate,
                                        paymentNotes = paymentNotes.trim(),
                                        totalAmount = amt,
                                        status = OrderStatus.PENDING_GODOWN_REVIEW,
                                        remarks = specialInstructions.trim(),
                                        createdAt = Date(),
                                        updatedAt = Date(),

                                        // Role specific and Item fields
                                        parcelId = orderNumber.trim(),
                                        otpVerified = true, // Godown intake verified
                                        itemName = itemName.trim(),
                                        itemDescription = itemDescription.trim(),
                                        length = lengthText.toDoubleOrNull() ?: 0.0,
                                        width = widthText.toDoubleOrNull() ?: 0.0,
                                        height = heightText.toDoubleOrNull() ?: 0.0,
                                        isFragile = isFragile,
                                        specialInstructions = specialInstructions.trim(),

                                        // Audit and creator fields
                                        createdBy = currentEmail,
                                        createdByUid = currentUid,
                                        createdByRole = "ADMIN003",
                                        source = "GODOWN_MANUAL_ENTRY"
                                    )

                                    viewModel.createOrder(newOrder)
                                },
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .height(54.dp),
                                shape = RoundedCornerShape(14.dp),
                                colors = ButtonDefaults.buttonColors(containerColor = Primary),
                                enabled = actionState !is Result.Loading
                            ) {
                                if (actionState is Result.Loading) {
                                    CircularProgressIndicator(modifier = Modifier.size(24.dp), color = Color.Black)
                                } else {
                                    Icon(Icons.Default.Save, contentDescription = null, tint = Color.Black)
                                    Spacer(modifier = Modifier.width(8.dp))
                                    Text("SAVE PARCEL", fontWeight = FontWeight.ExtraBold, fontSize = 15.sp, color = Color.Black)
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
